### ISSUE TITLE
Cannot open pubspec.yaml in pub cache

### ISSUE THREAD

**Issue by Reprevise** [invertase/dart_custom_lint#140]
In my `custom_lint.log` file, I constantly get this error:

I am on version 0.3.3 of `custom_lint`.

Yes, this path does exist on my system.

```
The request edit.getFixes failed with the following error:
RequestErrorCode.PLUGIN_ERROR
FileSystemException: Cannot open file, path = '/C:/Users/bscho/.puro/shared/pub_cache/hosted/pub.dev/auto_route_generator-5.0.3/pubspec.yaml' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
at:
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:7)
#2      _rootRunUnary (dart:async/zone.dart:1406:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#4      parsePubspec (package:custom_lint/src/package_utils.dart:81:24)
<asynchronous suspension>
#5      CustomLintPluginCheckerCache.isPlugin.<anonymous closure> (package:custom_lint/src/workspace.dart:387:23)
<asynchronous suspension>
#6      CustomLintProject.parse.<anonymous closure> (package:custom_lint/src/workspace.dart:535:26)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#8      CustomLintProject.parse (package:custom_lint/src/workspace.dart:526:21)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#10     CustomLintWorkspace.fromContextRoots (package:custom_lint/src/workspace.dart:236:22)
<asynchronous suspension>
#11     SocketCustomLintServerToClientChannel.create (package:custom_lint/src/v2/server_to_client_channel.dart:59:23)
<asynchronous suspension>
#12     CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:347:23)
<asynchronous suspension>
#13     CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:328:9)
<asynchronous suspension>
#14     PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#15     CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
FileSystemException: Cannot open file, path = '/C:/Users/bscho/.puro/shared/pub_cache/hosted/pub.dev/auto_route_generator-5.0.3/pubspec.yaml' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
at:
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:7)
#2      _rootRunUnary (dart:async/zone.dart:1406:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#4      parsePubspec (package:custom_lint/src/package_utils.dart:81:24)
<asynchronous suspension>
#5      CustomLintPluginCheckerCache.isPlugin.<anonymous closure> (package:custom_lint/src/workspace.dart:387:23)
<asynchronous suspension>
#6      CustomLintProject.parse.<anonymous closure> (package:custom_lint/src/workspace.dart:535:26)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#8      CustomLintProject.parse (package:custom_lint/src/workspace.dart:526:21)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#10     CustomLintWorkspace.fromContextRoots (package:custom_lint/src/workspace.dart:236:22)
<asynchronous suspension>
#11     SocketCustomLintServerToClientChannel.create (package:custom_lint/src/v2/server_to_client_channel.dart:59:23)
<asynchronous suspension>
#12     CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:347:23)
<asynchronous suspension>
#13     CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:328:9)
<asynchronous suspension>
#14     PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#15     CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>
```

**Comment by rrousselGit** [comment]
I'll need a way to reproduce this.
Could you maybe make a repository with whatever needed for this error to happen?

Nothing I can do otherwise.

**Comment by AxanIqbal** [comment]
having the same error
```
The request analysis.setSubscriptions failed with the following error:
RequestErrorCode.PLUGIN_ERROR
FileSystemException: Cannot open file, path = '/C:/flutter/packages/flutter_test/pubspec.yaml' (OS Error: The filename, directory name, or volume label syntax is incorrect.
, errno = 123)
at:
#0      _checkForErrorResponse (dart:io/common.dart:42:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:364:7)
#2      _rootRunUnary (dart:async/zone.dart:1406:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1307:19)
<asynchronous suspension>
#4      parsePubspec (package:custom_lint/src/package_utils.dart:81:24)
<asynchronous suspension>
#5      CustomLintPluginCheckerCache.isPlugin.<anonymous closure> (package:custom_lint/src/workspace.dart:387:23)
<asynchronous suspension>
#6      CustomLintProject.parse.<anonymous closure> (package:custom_lint/src/workspace.dart:535:26)
<asynchronous suspension>
#7      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#8      CustomLintProject.parse (package:custom_lint/src/workspace.dart:526:21)
<asynchronous suspension>
#9      Future.wait.<anonymous closure> (dart:async/future.dart:522:21)
<asynchronous suspension>
#10     CustomLintWorkspace.fromContextRoots (package:custom_lint/src/workspace.dart:236:22)
<asynchronous suspension>
#11     SocketCustomLintServerToClientChannel.create (package:custom_lint/src/v2/server_to_client_channel.dart:59:23)
<asynchronous suspension>
#12     CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:347:23)
<asynchronous suspension>
#13     CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:328:9)
<asynchronous suspension>
#14     PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#15     CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>
```
