### ISSUE TITLE
Opening the source of a dependency throws

### ISSUE THREAD

**Issue by rrousselGit** [invertase/dart_custom_lint#203]
From a discord report

When going to the definition of a clas from a package, it appears that an exception is thrown:
"Unable to find the context to <path/to/dependency>

**Comment by AlexV525** [comment]
Seeing this floods my log file:

```log
The request edit.getAssists failed with the following error:
RequestErrorCode.PLUGIN_ERROR
A request threw the exception:Bad state: Unable to find the context to /Users/alex/dev/.pub-cache/hosted/pub.flutter-io.cn/animations-2.0.11/lib/src/open_container.dart
#0      AnalysisContextCollectionImpl.contextFor (package:analyzer/src/dart/analysis/analysis_context_collection.dart:176:5)
#1      _ClientAnalyzerPlugin.handleEditGetAssists (package:custom_lint_builder/src/client.dart:509:47)
<asynchronous suspension>
#2      ServerPlugin._getResponse (package:analyzer_plugin/plugin/plugin.dart:554:18)
<asynchronous suspension>
#3      ServerPlugin._onRequest (package:analyzer_plugin/plugin/plugin.dart:597:18)
<asynchronous suspension>

at:
#0      SocketCustomLintServerToClientChannel.sendCustomLintRequest (package:custom_lint/src/v2/server_to_client_channel.dart:273:11)
<asynchronous suspension>
#1      SocketCustomLintServerToClientChannel.sendAnalyzerPluginRequest (package:custom_lint/src/v2/server_to_client_channel.dart:234:22)
<asynchronous suspension>
#2      CustomLintServer._handleRequest.<anonymous closure>.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:192:17)
<asynchronous suspension>
#3      PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#4      CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:175:22)
<asynchronous suspension>
```
