### ISSUE TITLE
Nested analysis_options throws when pubspec does not exist within same dir

### ISSUE THREAD

**Issue by mrgnhnt96** [invertase/dart_custom_lint#208]
According to the [Dart docs](https://arc.net/l/quote/cmuycoza)
> If the analyzer can’t find an analysis options file at the package root, it walks up the directory tree, looking for one. If no file is available, the analyzer defaults to standard checks.

In the example, they have the `analysis_options.yaml` in the same directory as the `pubspec.yaml`. However, whether this is intentional or not, the analyzer supports nested analysis options files without a `pubspec.yaml` within the same directory. The behavior of the nested analysis file works as you'd expect.

Take this folder structure for example

```tree
test
├── forbidden_imports
│   ├── analysis_options.yaml
│   ├── as_packages.dart
│   ├── as_paths.dart
│   └── custom_lint.log
├── single_class
│   └── contains_two_classes.dart
├── analysis_options.yaml
├── custom_lint.log
├── pubspec.lock
└── pubspec.yaml
```

At the root, we have a `pubspec.yaml` and `analysis_options.yaml` file, this is expected and functions as expected. In the `forbidden_imports` directory, there is a nested `analysis_options.yaml` containing specific configurations for this certain test. Since `dart_custom_lint` is expecting a pubspec file within the same directory, it throws.

<details>
<summary>Here is the error log</summary>

```console
The request analysis.updateContent failed with the following error:
RequestErrorCode.PLUGIN_ERROR
Failed to read pubspec.yaml at PATH/test/forbidden_imports:
PathNotFoundException: Cannot open file, path = 'PATH/test/forbidden_imports/pubspec.yaml' (OS Error: No such file or directory, errno = 2)
#0      _checkForErrorResponse (dart:io/common.dart:55:9)
#1      _File.open.<anonymous closure> (dart:io/file_impl.dart:381:7)
#2      _rootRunUnary (dart:async/zone.dart:1407:47)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308:19)
<asynchronous suspension>
#4      _File.readAsBytes.<anonymous closure> (dart:io/file_impl.dart:562:24)
<asynchronous suspension>
#5      _File.readAsString (dart:io/file_impl.dart:621:18)
<asynchronous suspension>
#6      parsePubspec (package:custom_lint/src/package_utils.dart:84:24)
<asynchronous suspension>
#7      CustomLintProject.parse (package:custom_lint/src/workspace.dart:980:28)
<asynchronous suspension>
#8      Future.wait.<anonymous closure> (dart:async/future.dart:523:21)
<asynchronous suspension>
#9      CustomLintWorkspace.fromContextRoots (package:custom_lint/src/workspace.dart:487:22)
<asynchronous suspension>
#10     SocketCustomLintServerToClientChannel.create (package:custom_lint/src/v2/server_to_client_channel.dart:54:23)
<asynchronous suspension>
#11     CustomLintServer._maybeSpawnCustomLintPlugin (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:347:23)
<asynchronous suspension>
#12     CustomLintServer._handleAnalysisSetContextRoots.<anonymous closure> (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:328:9)
<asynchronous suspension>
#13     PendingOperation.run (package:custom_lint/src/async_operation.dart:22:14)
<asynchronous suspension>
#14     CustomLintServer._handleRequest (package:custom_lint/src/v2/custom_lint_analyzer_plugin.dart:160:22)
<asynchronous suspension>

at:
#0      CustomLintProject.parse.<anonymous closure> (package:custom_lint/src/workspace.dart:983:7)
#1      _rootRunBinary (dart:async/zone.dart:1423:47)
#2      _CustomZone.runBinary (dart:async/zone.dart:1315:19)
#3      _FutureListener.handleError (dart:async/future_impl.dart:177:22)
#4      Future._propagateToListeners.handleError (dart:async/future_impl.dart:858:47)
#5      Future._propagateToListeners (dart:async/future_impl.dart:879:13)
#6      Future._completeError (dart:async/future_impl.dart:655:5)
<asynchronous suspension>
```
</details>

It would be beneficial to support nested `analysis_options.yaml` files, which would reflect the existing analyzer.
Supporting this would also help with writing tests with specific configurations without having to write new packages/pubspec files for every use case.

As a side note, the `custom_lint.log` file gets generated in the same directory as `analysis_options.yaml` instead of the `pubspec.yaml`, that should probably also be changed to avoid having multiple log files.

**To Reproduce**

- Copy the example_lint example provided in this repo
- Create a folder within `lib`
- Create a dart file & analysis_options.yaml (no config necessary)
- Run `custom_lint`
- See the exception found within the log, `custom_lint.log`

**Expected behavior**
I would expect the code to navigate up the tree in search of the `pubspec.yaml` file, if it doesn't exist within the directory with `analysis_options.yaml`.

**Comment by mrgnhnt96** [comment]
Closing this as this is a dup of #148
